CREATE USER username WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE appaka TO username;

CREATE USER repl WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE appaka TO repl;

CREATE USER jumbo_ro WITH ENCRYPTED PASSWORD 'password';
GRANT CONNECT ON DATABASE appaka TO jumbo_ro;

CREATE USER exasys_ro WITH ENCRYPTED PASSWORD 'password';
GRANT CONNECT ON DATABASE appaka TO exasys_ro;

CREATE USER metrics WITH ENCRYPTED PASSWORD 'password';
GRANT SELECT ON TABLE pg_stat_database TO metrics;

GRANT USAGE ON SCHEMA public TO username;
GRANT CREATE ON SCHEMA public TO username;
GRANT ALL ON ALL TABLES IN SCHEMA public TO username;
