version: "3.4"

services:

  node:
    image: node
    working_dir: /srv/appaka
    volumes:
      - ./front:/srv/appaka
    command: yarn start
    ports:
      - "80:3000"

  elixir:
    image: elixir:1.6.6
    working_dir: /usr/src/myapp
    volumes:
      - ./elixir:/usr/src/myapp
      - ./elixir/.mix:/root/.mix
    networks:
      - appaka
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ecto://username:password@postgres/appaka
    command: |
      mix phx.server
    ports:
      - 4000:4000

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appaka
    volumes:
      - ./docker/db-fixtures/:/docker-entrypoint-initdb.d/:delegated
      - ./.docker/postgres/:/var/lib/postgresql/data
    networks:
      - appaka
    ports:
      - 5432:5432

networks: 
  appaka:
    

