version: "3.4"

services:

  node:
    image: node:13.2.0
    working_dir: /srv/appaka
    volumes:
      - ./front:/srv/appaka
    command: start
    entrypoint: /srv/appaka/entrypoint.sh
    ports:
      - "80:3000"

  elixir:
    image: elixir:1.6.6
    working_dir: /usr/src/myapp
    volumes:
      - ./elixir:/usr/src/myapp
      - ./elixir/.mix:/root/.mix
    depends_on:
      - postgres
    command: mix phx.server
    entrypoint: /usr/src/myapp/entrypoint.sh
    environment:
      DATABASE_URL: ecto://username:password@postgres/appaka
      OPSGENIE_API_KEY: "${OPSGENIE_API_KEY}"
    ports:
      - 4000:4000

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appaka
    volumes:
      - ./docker/db-fixtures/:/docker-entrypoint-initdb.d/:delegated
      - postgres:/var/lib/postgresql/data
    ports:
      - 54320:5432

volumes:
  postgres:
